# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
    - package-ecosystem: "composer"
      target-branch: "master"
      directory: "/"
      versioning-strategy: "increase-if-necessary"
      open-pull-requests-limit: 10
      schedule:
          interval: "daily"
      assignees:
          - "zerai"
      commit-message:
          include: "scope"
          prefix: "composer"
      labels:
          - "php dependency"


    #
    # Tools dependecy track
    #
    - package-ecosystem: "composer"
      target-branch: "master"
      directory: "/tools/ecs"
      versioning-strategy: "increase-if-necessary"
      open-pull-requests-limit: 3
      schedule:
          interval: "daily"
      assignees:
          - "zerai"
      commit-message:
          include: "scope"
          prefix: "composer"
      labels:
          - "tool dependency"


    - package-ecosystem: "composer"
      target-branch: "master"
      directory: "/tools/phpstan"
      versioning-strategy: "increase-if-necessary"
      open-pull-requests-limit: 3
      schedule:
          interval: "daily"
      assignees:
          - "zerai"
      commit-message:
          include: "scope"
          prefix: "composer"
      labels:
          - "tool dependency"


    - package-ecosystem: "composer"
      target-branch: "master"
      directory: "/tools/psalm"
      versioning-strategy: "increase-if-necessary"
      open-pull-requests-limit: 3
      schedule:
          interval: "daily"
      assignees:
          - "zerai"
      commit-message:
          include: "scope"
          prefix: "composer"
      labels:
          - "tool dependency"

